# Generated by Django 2.2.5 on 2022-01-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
